### ISSUE TITLE
Issue template da organização não funciona em repositórios que também tenham Issues templates

### ISSUE THREAD

**Issue by gabrielbdornas** [splor-mg/.github#2]
### Descrição

Nesta [discussão na comunidade GiHub](https://github.com/orgs/community/discussions/22451), consegui descobrir que é possível [criar arquivos em comum para todos os repositórios de uma organização](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file).

> You can create default community health files, such as CONTRIBUTING and CODE_OF_CONDUCT. Default files will be used for any repository owned by the account that does not contain its own file of that type.

A partir deste conceito, criei este repositório para incluir o template de Issues que utilizaremos na AID[^1][^2], conforme sugerido na [Reunião organização trabalho AID - Gestão à Vista](https://github.com/splor-mg/reunioes/issues/62).

Como nem tudo são :rose:, encontrei um problema: quando o repositório já tem Issue(s) template(s), o definido globalmente não funciona:

> If a repository has any files in its own .github/ISSUE_TEMPLATE folder, including issue templates or a config.yml file, none of the contents of the default .github/ISSUE_TEMPLATE folder will be used.

Descobri isso com @carloshob olhando o [handbook](https://github.com/splor-mg/handbook/issues).

Um workaround seria retirar os templates dos repositórios e deixá-los no nível da organização. O problema disso é que ficaria estranho ver um template `Onboarding` toda vez que for criar um Issue.

Acho que o ganho em se ter padronizado o template de Issues que utilizaremos na AID supera a estranheza de ver o template `Onboarding` toda vez que for criar um Issue, mas gostaria da opinião do resto da equipe (@splor-mg/aid).

[^1]: Criei também um template para Atas de Reunião.
[^2]: [Documentação Issue Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) e opções de [configuração para permissão da utilização de Issues sem template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser).

### Lista de atividades e/ou correções

- [x] Opinião da equipe.
- [x] Possibilidade de outros workaround.
- [x] Abrir sugestão [comunidade](https://github.com/orgs/community/discussions).
- [x] Implantar workaround sugerido no comentário inicial ou outra opção posterior melhor.

### Participantes

@splor-mg/aid, @labanca, @carloshob, @gabrielbdornas, @hslinhares

**Comment by gabrielbdornas** [comment]
Não foi necessário abrir sugestão na [comunidade](https://github.com/orgs/community/discussions), pois já [havia este pedido por lá](https://github.com/orgs/community/discussions/16383). A má notícia é que o pedido não tem muita interação. O que indica que dificilmente será desenvolvido. 

Sendo assim, o primeiro workaround ainda é a melhor opção para o momento.

**Comment by hslinhares** [comment]
@gabrielbdornas achei a experiência de usar o template pro issue boa, nenhuma estranheza. Reforça o o conteúdo mínimo esperado.

**Comment by gabrielbdornas** [comment]
> Acho que o ganho em se ter padronizado o template de Issues que utilizaremos na AID supera a estranheza de ver o template `Onboarding` toda vez que for criar um Issue, mas gostaria da opinião do resto da equipe (@splor-mg/aid).

@splor-mg/aid, talvez uma alternativa (workaround) seja criar nos repos com issues específicos os mesmo Issues do repo `.github`. Repetiremos código, mas não estou vendo outra alternativa.
